### pytorch

Torch is that developed Lua language changed into python language.

torch : main name space, tensor, math functions.

torch.autograd: automatic differential 

torch.nn : data structure and layers for build network

torch.optim : SGD(Stochasic Gradient Descent)

torch.utils : offer the data utilities

torch.ONNX(Open Neural Network Exchange) : when using share the different model

In [1]:
import torch

torch.__version__

'1.13.1+cpu'

In [2]:
x = torch.empty(4,2)
print(x)

tensor([[5.2942e-15, 1.0384e-42],
        [5.2942e-15, 1.0384e-42],
        [1.0675e-13, 1.0384e-42],
        [1.0675e-13, 1.0384e-42]])


In [3]:
x = torch.rand(4,2)

In [4]:
print(x)

tensor([[0.8509, 0.6354],
        [0.9326, 0.5473],
        [0.7556, 0.4183],
        [0.6797, 0.6097]])


In [6]:
# date type = long, fill in 0

x = torch.zeros(4,2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
x = torch.ones(2,4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [8]:
x = torch.randn_like(x, dtype=float)
print(x)

tensor([[-0.6744, -0.0386, -0.9620,  0.9163],
        [-0.8388, -0.3138, -1.7464, -1.1460]], dtype=torch.float64)


### Data type

In [10]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [11]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [12]:
it = torch.IntTensor([1,2,3])
print(it.float())
print(it.double())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)


### CUDA Tensor

using method .to , tensor can move any one(cpu, gpu)

In [14]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.9514])
0.9514175057411194
torch.float32


In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [16]:
print(device)
y = torch.ones_like(x, device = device)
print(y)
x = x.to(device)
print(x)
z = x+y
print(z)
print(x.to('cpu', torch.double))

cpu
tensor([1.])
tensor([0.9514])
tensor([1.9514])
tensor([0.9514], dtype=torch.float64)


In [17]:
# 0D tensor

t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [18]:
# 1D tensor

t1 = torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [21]:
# 2D tensor

t2 = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [22]:
# 3D tensor : stock dataset, disease dataset by time series...

t3 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
# 4D tensor : color channel (samples, height, width, channel(rgb))
# 5D tensor : video (sample, frames, height, width, channel)

### Tensor Operations

In [25]:
import math

a = torch.rand(1,2) * 2 - 1

In [29]:
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))


tensor([[-0.4993,  0.2241]])
tensor([[0.4993, 0.2241]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.4993,  0.2241]])


In [30]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,4,3,2,1,])))

tensor([[-0.4993,  0.2241]])
tensor(-0.4993)
tensor(0.2241)
tensor(-0.1376)
tensor(0.5115)
tensor(-0.1119)
tensor([1, 2, 3, 4])


In [32]:
# max, min : if you give an index, argmax and argmin return.

x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.2275, 0.0239],
        [0.7238, 0.4096]])
torch.return_types.max(
values=tensor([0.7238, 0.4096]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.2275, 0.7238]),
indices=tensor([0, 0]))


In [33]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.2275, 0.0239],
        [0.7238, 0.4096]])
torch.return_types.min(
values=tensor([0.2275, 0.0239]),
indices=tensor([0, 0]))
torch.return_types.min(
values=tensor([0.0239, 0.4096]),
indices=tensor([1, 1]))


inplace way

x.copy_(y), x.t_()

In [34]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print(x.add(y))

tensor([[0.2939, 0.9434],
        [0.3833, 0.3153]])
tensor([[0.1970, 0.6013],
        [0.7187, 0.0235]])
tensor([[0.4908, 1.5447],
        [1.1020, 0.3388]])


In [37]:
print(x)
print(y)
print(x.add(y))
print(y.add_(x))
print(x)
print(y)

tensor([[0.2939, 0.9434],
        [0.3833, 0.3153]])
tensor([[0.4908, 1.5447],
        [1.1020, 0.3388]])
tensor([[0.7847, 2.4882],
        [1.4853, 0.6541]])
tensor([[0.7847, 2.4882],
        [1.4853, 0.6541]])
tensor([[0.2939, 0.9434],
        [0.3833, 0.3153]])
tensor([[0.7847, 2.4882],
        [1.4853, 0.6541]])


In [ ]:
# mul, div, matmul(dot product)

Tensor Manipulations

* slicing
* indexing

In [38]:
x = torch.Tensor([[1,2],[3,4]])
print(x[0,1])
print(x[1,1])

tensor(2.)
tensor(4.)


In [39]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)

tensor([[-2.0628,  1.5145, -0.2660, -0.8447,  0.4475],
        [ 1.4215, -0.4408, -0.2060, -0.0882, -0.9263],
        [ 0.5379,  0.0263, -1.6666,  0.7223,  0.7709],
        [ 0.6136, -1.2489, -0.2304,  0.6544,  1.1714]])
tensor([-2.0628,  1.5145, -0.2660, -0.8447,  0.4475,  1.4215, -0.4408, -0.2060,
        -0.0882, -0.9263,  0.5379,  0.0263, -1.6666,  0.7223,  0.7709,  0.6136,
        -1.2489, -0.2304,  0.6544,  1.1714])


item : 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음

In [41]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.1310])
1.130972981452942
torch.float32


### squeeze :  vector reduction(remove)

In [42]:
tensor = torch.rand(1,3,3)
print(tensor)
print(tensor.shape)

tensor([[[0.4190, 0.3405, 0.1598],
         [0.5945, 0.2925, 0.6121],
         [0.0057, 0.5270, 0.4351]]])
torch.Size([1, 3, 3])


In [43]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.4190, 0.3405, 0.1598],
        [0.5945, 0.2925, 0.6121],
        [0.0057, 0.5270, 0.4351]])
torch.Size([3, 3])


In [44]:
# unsqueeze

tensor = t. unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.4190, 0.3405, 0.1598],
         [0.5945, 0.2925, 0.6121],
         [0.0057, 0.5270, 0.4351]]])
torch.Size([1, 3, 3])


In [45]:
tensor = t. unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.4190],
         [0.3405],
         [0.1598]],

        [[0.5945],
         [0.2925],
         [0.6121]],

        [[0.0057],
         [0.5270],
         [0.4351]]])
torch.Size([3, 3, 1])


In [47]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [48]:
# cat (concatenate) : similar stack

a = torch.randn(1,3,3)
b= torch.randn(1,3,3)
print(torch.cat((a,b), dim = 0))
print(torch.cat((a,b), dim = 1))
print(torch.cat((a,b), dim = 2))

tensor([[[-0.5906,  0.7350,  0.2643],
         [ 0.1712, -1.6206, -0.5989],
         [-0.7059, -0.6261, -4.1033]],

        [[ 0.3489, -1.1528, -0.9685],
         [ 2.1626, -1.2802,  0.2717],
         [-0.2347, -1.4900, -1.5965]]])
tensor([[[-0.5906,  0.7350,  0.2643],
         [ 0.1712, -1.6206, -0.5989],
         [-0.7059, -0.6261, -4.1033],
         [ 0.3489, -1.1528, -0.9685],
         [ 2.1626, -1.2802,  0.2717],
         [-0.2347, -1.4900, -1.5965]]])
tensor([[[-0.5906,  0.7350,  0.2643,  0.3489, -1.1528, -0.9685],
         [ 0.1712, -1.6206, -0.5989,  2.1626, -1.2802,  0.2717],
         [-0.7059, -0.6261, -4.1033, -0.2347, -1.4900, -1.5965]]])


In [49]:
# chunk : tensor divide

tensor = torch.rand(3,6)
print(tensor)

t1,t2,t3 = torch.chunk(tensor, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.8044, 0.3660, 0.6623, 0.3411, 0.9194, 0.0951],
        [0.7112, 0.8663, 0.7820, 0.1303, 0.4551, 0.1317],
        [0.2898, 0.2501, 0.4043, 0.8421, 0.3995, 0.2774]])
tensor([[0.8044, 0.3660],
        [0.7112, 0.8663],
        [0.2898, 0.2501]])
tensor([[0.6623, 0.3411],
        [0.7820, 0.1303],
        [0.4043, 0.8421]])
tensor([[0.9194, 0.0951],
        [0.4551, 0.1317],
        [0.3995, 0.2774]])


In [50]:
# split

tensor = torch.rand(3,6)
t1,t2 = torch.split(tensor, 3, dim = 1)

print(tensor)
print(t1)
print(t2)

tensor([[0.2449, 0.6035, 0.0429, 0.3931, 0.9625, 0.2410],
        [0.6332, 0.6812, 0.7653, 0.3612, 0.7872, 0.8076],
        [0.5024, 0.2274, 0.1420, 0.5750, 0.5144, 0.8667]])
tensor([[0.2449, 0.6035, 0.0429],
        [0.6332, 0.6812, 0.7653],
        [0.5024, 0.2274, 0.1420]])
tensor([[0.3931, 0.9625, 0.2410],
        [0.3612, 0.7872, 0.8076],
        [0.5750, 0.5144, 0.8667]])


### Autograd(자동미분)

### Gradient

In [52]:
x = torch.ones(3,3, requires_grad = True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [53]:
y = x+5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [54]:
z = y*y
out = z.mean()
print(out)

tensor(36., grad_fn=<MeanBackward0>)


In [55]:
print(out)
out.backward()

tensor(36., grad_fn=<MeanBackward0>)


In [56]:
print(x)
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [57]:
x = torch.randn(3, requires_grad = True)

y = x*2
while y.data.norm() < 1000:
    y = y*2

print(y)

tensor([-804.7925,  324.6097, -818.2330], grad_fn=<MulBackward0>)


In [61]:
# with torch.no_grad() : 기울기를 계산하지 않음
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


### dataset (MNIST)

In [62]:
from torch.utils.data import Dataset, DataLoader

In [68]:
!pip3 install torchvision

     ---------------------------------------- 1.1/1.1 MB 11.5 MB/s eta 0:00:00


In [69]:
# transforms : when we do data preprocessing

import torchvision.transforms as transforms
from torchvision import datasets

In [70]:
mnist_transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize(mean = (0.5,), std = (1.0,))])

In [72]:
trainset = datasets.MNIST(root = '/content/', train = True, download=True, transform = mnist_transform)
testset = datasets.MNIST(root = '/content/', train = False, download=True, transform = mnist_transform)


In [73]:
train_loader = DataLoader(trainset, batch_size = 8, shuffle = True, num_workers = 2)
test_loader = DataLoader(testset, batch_size = 8, shuffle = False, num_workers = 2)

In [80]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [81]:
print(device)

cpu


In [82]:
classes = ('zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine')

In [101]:
# implement conv net
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 5, 5) # 1 channels, 6 filters, 5x5 filter size
        self.pool = nn.MaxPool2d(2,2) #size 2X2, stride: 2
        self.conv2 = nn.Conv2d(6, 14, 5)
        self.fc1 = nn.Linear(14*4*4, 120) #16*5*5= number of output channels * dimension of the output layer after feature learning; 120 manually set as outcome of the 
        self.fc2 = nn.Linear(120, 60)
        self.fc3 = nn.Linear(60, 10) #the output dimension (in our case 10) needs to be equal to the number of classes
    
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, ) #torch.view() function freshape the input tensor
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
model = ConvNet().to(device)

In [85]:
# Hyper-parameters of the model
num_epochs = 4
batch_size = 4
learning_rate = 0.003

In [86]:
criterion = nn.CrossEntropyLoss() #CrossEntropyLoss already includes SoftMax
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [102]:
n_total_steps = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):
        # origin shape: [4, 3, 32, 32] = 4, 3, 1024
        # input_layer: 1 input channels, 6 output channels, 5 kernel size
        images = images.to(device)
        labels = labels.to(device)

        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad() #with zero_grad() we ensure that the gradients are properly reset to zero at the start of each iteration
        loss.backward()
        optimizer.step()
        #wandb.log({"loss": loss})  uncomment this line if you want to send data to weights and biases interface


        if (i+1) % 2000 == 0:
            print (f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{n_total_steps}], Loss: {loss.item():.4f}')
            # Calculate average accuracy for every 2000 steps
            model.eval()
            with torch.no_grad():
                correct = 0
                total = 0
                for images, labels in test_loader:
                    images = images.to(device)
                    labels = labels.to(device)
                    outputs = model(images)
                    _, predicted = torch.max(outputs.data, 1)
                    total += labels.size(0)
                    correct += (predicted == labels).sum().item()
                accuracy = correct / total
                #wandb.log({"accuracy": accuracy}) uncomment this line if you want to send data to weights and biases interface
        
print('Finished Training')
PATH = './cnn.pth'
torch.save(model.state_dict(), PATH)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x1792 and 350x120)